In [1]:
import numpy as np

In [54]:
a=90 * np.pi / 180 #угол 20 град.
Ax=[[1,0,0],[0,np.cos(a),-np.sin(a)],[0,np.sin(a),np.cos(a)]]
Ay=[[np.cos(a),0,np.sin(a)],[0,1,0],[-np.sin(a),0,np.cos(a)]]
Az=[[np.cos(a),-np.sin(a),0],[np.sin(a),np.cos(a),0],[0,0,1]]

In [55]:

Ax

[[1, 0, 0], [0, 6.123233995736766e-17, -1.0], [0, 1.0, 6.123233995736766e-17]]

In [13]:
Ay

[[1.0, 0, 0.0], [0, 1, 0], [-0.0, 0, 1.0]]

In [14]:
Az

[[1.0, -0.0, 0], [0.0, 1.0, 0], [0, 0, 1]]

In [37]:
root=np.array([10.4194, 16.7048, -30.1003, -2.48972, -9.82194, -3.00914])

In [38]:
root_cor=root[0:3]
root_orient=root[3:6]
new_root_cor=root_cor
new_root_orient=root_orient

In [40]:
for i in range(len(root_cor)):
    joint = root_cor[i]
    new_root_cor[i]=root_cor[i]-root_cor[i]

In [47]:
new_root_cor = new_root_cor.reshape(1, len(new_root_cor))

In [48]:
new_root_cor

array([[0., 0., 0.]])

даьше ориентацию переводим в матрицы поворота


In [60]:

a=new_root_orient[0] * np.pi / 180 #угол 20 град.
b=new_root_orient[1] * np.pi / 180 #угол 20 град.
c=new_root_orient[2] * np.pi / 180 #угол 20 град.

Ax=np.array([[1,0,0],[0,np.cos(a),-np.sin(a)],[0,np.sin(a),np.cos(a)]])
Ay=np.array([[np.cos(b),0,np.sin(b)],[0,1,0],[-np.sin(b),0,np.cos(b)]])
Az=np.array([[np.cos(c),-np.sin(c),0],[np.sin(c),np.cos(c),0],[0,0,1]])
S=np.dot(np.dot(Ax,Ay), Az)

In [61]:
Ax=np.array([[1,0,0],[0,np.cos(a),-np.sin(a)],[0,np.sin(a),np.cos(a)]])*Az
S=Ax*Ay

array([[ 0.98398403,  0.        , -0.        ],
       [-0.        ,  0.99767851,  0.        ],
       [ 0.        , -0.        ,  0.98441252]])

In [62]:
Ax=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [75]:


# S

array([[0.99862117, 0.05249526, 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ]])

In [74]:
Az

array([[ 0.99862117,  0.05249526,  0.        ],
       [-0.05249526,  0.99862117,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])